# Generated by Django 6.1 on 2026-09-02 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint Push')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Clé publique p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='Clé auth')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement Web Push',
                'verbose_name_plural': 'Abonnements Web Push',
                'ordering': ['-created_at'],
            },
        ),
    ]
