# Generated by Django 6.1 on 2026-08-26 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la boutique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
            },
        ),
        migrations.CreateModel(
            name='ShopBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#7C3AED', max_length=7, verbose_name='Couleur principale')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='shop.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Identité visuelle',
                'verbose_name_plural': 'Identités visuelles',
            },
        ),
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mobile_money', '📱 Mobile Money (MTN, Orange, Wave…)'), ('livraison', '🚚 Paiement à la livraison'), ('virement', '🏦 Virement bancaire')], default='livraison', max_length=30, verbose_name='Moyen de paiement')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='Clé API (Optionnel)')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nom du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
