# Generated by Django 6.1 on 2026-08-26 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='shopbranding',
            options={'verbose_name': 'Identité visuelle', 'verbose_name_plural': 'Identités visuelles'},
        ),
        migrations.AlterModelOptions(
            name='shoppayment',
            options={'verbose_name': 'Configuration de paiement', 'verbose_name_plural': 'Configurations de paiement'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom de la boutique'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='primary_color',
            field=models.CharField(default='#7C3AED', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='shop.shop', verbose_name='Boutique'),
        ),
        migrations.AlterField(
            model_name='shoppayment',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clé API (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='shoppayment',
            name='gateway',
            field=models.CharField(choices=[('mobile_money', '📱 Mobile Money (MTN, Orange, Wave…)'), ('livraison', '🚚 Paiement à la livraison'), ('virement', '🏦 Virement bancaire')], default='livraison', max_length=30, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='shoppayment',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.shop', verbose_name='Boutique'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop', verbose_name='Boutique'),
        ),
    ]
