# Generated by Django 6.1 on 2026-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppayment',
            name='gateway',
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='accepted_payments',
            field=models.JSONField(default=list, verbose_name='Moyens de paiement acceptés'),
        ),
    ]
