# Generated by Django 6.1 on 2026-08-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shoppayment_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Lien Direct'), ('qr', 'QR Code')], default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shop.shopproduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shop.shop')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
            },
        ),
    ]
