# Generated by Django 6.1 on 2026-08-27 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_visittracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='shoppayment',
            options={'verbose_name': 'Configuration de paiement & livraison', 'verbose_name_plural': 'Configurations de paiement & livraison'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='visittracker',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visite', 'verbose_name_plural': 'Visites'},
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(default='Mode & Habillement', max_length=80, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Abidjan', max_length=80, verbose_name='Ville / Commune'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Boutique active'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, help_text='Ex: +225 0700000000', max_length=25, verbose_name='Numéro WhatsApp pour commandes'),
        ),
        migrations.AddField(
            model_name='shopbranding',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shop_banners/', verbose_name='Bannière'),
        ),
        migrations.AddField(
            model_name='shopbranding',
            name='slogan',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='accepted_delivery_zones',
            field=models.JSONField(blank=True, default=list, help_text='Liste des communes/villes desservies', verbose_name='Zones de livraison'),
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Frais de livraison par défaut (FCFA)'),
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Livraison offerte à partir de (FCFA)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(blank=True, default='Général', max_length=80, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix barré / Promo (FCFA)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du produit'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible en stock'),
        ),
        migrations.AddField(
            model_name='visittracker',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='primary_color',
            field=models.CharField(default='#7C3AED', max_length=7, verbose_name='Couleur principale (HEX)'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='visittracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de visite'),
        ),
        migrations.AlterField(
            model_name='visittracker',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shop.shopproduct', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='visittracker',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shop.shop', verbose_name='Boutique'),
        ),
        migrations.AlterField(
            model_name='visittracker',
            name='source',
            field=models.CharField(choices=[('direct', 'Lien Direct / Bio'), ('qr', 'QR Code Flash'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='direct', max_length=20, verbose_name="Canal d'accès"),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de commande')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Téléphone WhatsApp')),
                ('customer_city', models.CharField(max_length=80, verbose_name='Commune / Ville')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Précision adresse / Carrefour / Repère')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de livraison (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total TTC (FCFA)')),
                ('status', models.CharField(choices=[('pending', '🟡 Reçue (En attente)'), ('confirmed', '🔵 Confirmée'), ('shipped', '🟣 En livraison / En route'), ('delivered', '🟢 Livrée'), ('cancelled', '🔴 Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('livraison', 'Paiement à la livraison (Cash)'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money')], default='livraison', max_length=30, verbose_name='Mode de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name="Nom du produit au moment de l'achat")),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total ligne (FCFA)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.shopproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
