# Generated by Django 6.1 on 2026-08-28 15:22

import apps.shop.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_options_alter_shoppayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranding',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.shop.models.shop_banner_path, verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.shop.models.shop_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.shop.models.product_image_path, verbose_name='Image principale'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.shop.models.secondary_product_image_path, verbose_name='Image supplémentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shopproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['created_at'],
            },
        ),
    ]
