# Generated by Django 6.1 on 2026-08-28 15:40

import apps.shop.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopbranding_banner_alter_shopbranding_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(max_length=255, upload_to=apps.shop.models.secondary_product_image_path, verbose_name='Image supplémentaire'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=255, null=True, upload_to=apps.shop.models.shop_banner_path, verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='shopbranding',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=255, null=True, upload_to=apps.shop.models.shop_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=255, null=True, upload_to=apps.shop.models.product_image_path, verbose_name='Image principale'),
        ),
    ]
