# Generated by Django 6.1 on 2026-08-29 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productimage_image_alter_shopbranding_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantité en stock'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Suivre le stock'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('new_order', '📦 Nouvelle commande'), ('low_stock', '⚠️ Stock faible'), ('out_of_stock', '🔴 Rupture de stock'), ('system', 'ℹ️ Information système')], default='new_order', max_length=30, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='shop.order', verbose_name='Commande associée')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.shop', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
