# Generated by Django 6.1 on 2026-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopproduct_stock_shopproduct_track_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name_last_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification du nom'),
        ),
    ]
